name: Update Configs
permissions: write-all

on:
  push:
    branches:
      - main
  schedule:
    # Run every 10 minutes
    - cron: "*/30 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: cd Files && pip install -r requirements.txt

    - name: Run Config script and save output to file
      run: cd Files && python app.py
      
    - name: Run Warp script and save output to file
      run: cd Files && python warp.py
      
    - name: Run Splitter script and save output to file
      run: cd Files && python sort.py

    - name: Commit and push files
      uses: EndBug/add-and-commit@v9
      with:
        author_name: "Github Actions"
        author_email: "actions@github.com"
        message: "Updated 9 minutes Ago 🫂"
        add: "."
        push: "https://github.com/hjz888/V2ray-Configs.git"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      
